### ISSUE TITLE
询问typecho的api相关情况

### ISSUE THREAD

**Issue by yegetables** [jianyuyouhun/typecho-api#1]
我也想写一个ssm的前后端分离项目，前端预计使用typecho的主题，现在想替换主题的数据接口json为Controller层提供的，但是不知道都要什么接口和内容，老哥你的user接口是怎么找的？有没有推荐的资料来源。

**Comment by jianyuyouhun** [comment]
自己翻typecho的源代码整理出来的，我当时就是学习一下typecho的登录身份验证怎么做的，然后自己用java实现了一版。后面就没怎么看了
